name: GitHub Actions Demo
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npx prettier . --check
      - run: npm test
      - run: npm ci
      - run: npm run lint