name: Node.js CI

on:
  pull_request:
    branches: ['main', 'nova-pagina']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npx prettier . --write
      - run: npm run test
      - run: npx prettier . --check
      - run: npm run lint

  production-deploy:
    if: github.repository == 'main' && ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: deploy
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

